version: "3"

services:
  postgres:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: dwb
    volumes:
      - '/home/niels/docker/dwb/db-data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
  api:
    depends_on:
      - postgres
    image: dwb
    ports:
      - "8000:8000"
    restart: always

